**Importing numpy:**

In [5]:
import numpy as np

**Creating a numpy array:**

In [6]:
a = np.array([100,200,250,300])
a

array([100, 200, 250, 300])

**Creating a 2-d array:**

*Attributes are*
**#shape**
**#ndim**
__#size__

**Creating an array**

In [7]:
b = np.array([[1,2,5],[3,4,6]])

**Printing the array**

In [8]:
b

array([[1, 2, 5],
       [3, 4, 6]])

**Shape of the array**

In [9]:
b.shape

(2, 3)

**Size of the array (No. of elements)**

In [10]:
b.size

6

**Dimension of the array**

In [11]:
b.ndim

2

**Indexing an array**

In [12]:
b[(0,1)]

2

**Creating a 3-d array:**

In [13]:
c = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])

In [14]:
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

**There are 2 matrices of order 3*4**

In [15]:
c.shape

(2, 3, 4)

In [16]:
c.size

24

In [17]:
c.ndim

3

**Creating an array of dim 2 * 3 * 4 and filling all elements as zeros**

In [18]:
d = np.zeros((4,2,3)) #deault type is float
d

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

**Creating an array and filling the array with random values**

In [19]:
e = np.empty((4,2), dtype=int)
e

array([[         0,          0],
       [1040185904,        417],
       [1040185200,        417],
       [1040186352,        417]])

**Creating a matrix f with dimensions of e and filling it with all 1s**

In [20]:
f = np.ones_like(e)
f

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

**Range function in python is like arange in numpy (but parameters can be float)**

In [21]:
np.arange(2,8,0.5)

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5])

**Creating an array with 8 evenly spaced values in the given range**

In [22]:
np.linspace(1,20,8).reshape(4,2)

array([[ 1.        ,  3.71428571],
       [ 6.42857143,  9.14285714],
       [11.85714286, 14.57142857],
       [17.28571429, 20.        ]])

**Creating an array with 8 evenly spaced values in the given range and returning the difference between 2 elements**

In [23]:
np.linspace(1,20,8, retstep=True)

(array([ 1.        ,  3.71428571,  6.42857143,  9.14285714, 11.85714286,
        14.57142857, 17.28571429, 20.        ]),
 2.7142857142857144)

**Same as previous, but excluding the end element**

In [24]:
np.linspace(1,20,8, endpoint=False)

array([ 1.   ,  3.375,  5.75 ,  8.125, 10.5  , 12.875, 15.25 , 17.625])

**Defining a function**

In [27]:
def func(i,j):
    return i+j

**Creating an array using fromfunction method**

In [28]:
np.fromfunction(func,(4,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 5.]])